//! PostcardOApp: raw LayerZero messaging on Stellar, no tokens involved.
//!
//! * `send_postcard` — the caller authorizes, we hand the UTF-8 bytes to the
//!   endpoint via the OApp send path (`__lz_send`), paying the quoted XLM fee.
//! * `lz_receive` (generated by `#[oapp]`) validates the peer, clears the
//!   payload on the endpoint, then calls our `__lz_receive`, which stores the
//!   postcard in a ring buffer of 50 and emits an event.
//!
//! The shape is the same one the USDT0 OFT uses; the payload is just text.
#![no_std]

use common_macros::{contract_impl, lz_contract};
use endpoint_v2::{MessagingFee, Origin};
use oapp::{
    oapp_core::{init_ownable_oapp, OAppCore},
    oapp_options_type3::OAppOptionsType3,
    oapp_receiver::{LzReceiveInternal, OAppReceiver},
    oapp_sender::{FeePayer, OAppSenderInternal},
};
use oapp_macros::oapp;
use soroban_sdk::{contracterror, contracttype, panic_with_error, symbol_short, Address, Bytes, BytesN, Env, Vec};

pub const MAX_TEXT_LEN: u32 = 140;
/// Message type used for enforced options (1 = SEND, like OFTs).
pub const SEND_MSG_TYPE: u32 = 1;
pub const MAX_POSTCARDS: u32 = 50;

#[contracterror]
#[derive(Copy, Clone, Debug, Eq, PartialEq, PartialOrd, Ord)]
#[repr(u32)]
pub enum PostcardError {
    /// The text is longer than 140 bytes.
    TooLong = 9001,
    /// Empty postcards are not worth a cross-chain message.
    Empty = 9002,
}

#[contracttype]
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct Postcard {
    pub src_eid: u32,
    /// 32-byte LayerZero sender (the peer OApp address on the source chain).
    pub sender: BytesN<32>,
    pub guid: BytesN<32>,
    pub text: Bytes,
    pub ledger: u32,
    pub timestamp: u64,
}

#[contracttype]
#[derive(Clone)]
pub enum DataKey {
    Postcards,
    Sent,
    Received,
}

#[lz_contract]
#[oapp]
pub struct PostcardOApp;

#[contract_impl]
impl PostcardOApp {
    /// `owner` may set peers / enforced options; `delegate` may change endpoint config (set_config).
    pub fn __constructor(env: &Env, owner: &Address, endpoint: &Address, delegate: &Address) {
        init_ownable_oapp::<Self>(env, owner, endpoint, delegate);
    }

    /// Price a postcard to `dst_eid`. `options` may be empty: the OApp prepends its enforced options
    /// (ULN302 rejects an empty options blob, which is exactly what enforced options are for).
    pub fn quote_postcard(env: &Env, dst_eid: u32, text: &Bytes, options: &Bytes, pay_in_zro: bool) -> MessagingFee {
        Self::check_text(env, text);
        let options = Self::combine_options(env, dst_eid, SEND_MSG_TYPE, options);
        Self::__quote(env, dst_eid, text, &options, pay_in_zro)
    }

    // snippet:start sendPostcardRust
    /// Send a postcard. `caller` pays the XLM fee and receives any refund. Returns the message GUID.
    pub fn send_postcard(env: &Env, caller: &Address, dst_eid: u32, text: &Bytes, options: &Bytes, fee: &MessagingFee) -> BytesN<32> {
        caller.require_auth();
        Self::check_text(env, text);
        let options = Self::combine_options(env, dst_eid, SEND_MSG_TYPE, options);
        // FeePayer::Verified: we already called require_auth, so the send path must not ask again.
        let receipt = Self::__lz_send(env, dst_eid, text, &options, &FeePayer::Verified(caller.clone()), fee, caller);
        let sent: u64 = env.storage().instance().get(&DataKey::Sent).unwrap_or(0);
        env.storage().instance().set(&DataKey::Sent, &(sent + 1));
        env.events().publish((symbol_short!("pc_sent"), dst_eid, caller.clone()), (receipt.guid.clone(), text.clone()));
        receipt.guid
    }
    // snippet:end sendPostcardRust

    /// The last 50 postcards received, newest first.
    pub fn postcards(env: &Env) -> Vec<Postcard> {
        env.storage().instance().get(&DataKey::Postcards).unwrap_or(Vec::new(env))
    }

    /// (sent, received) counters.
    pub fn counts(env: &Env) -> (u64, u64) {
        let sent: u64 = env.storage().instance().get(&DataKey::Sent).unwrap_or(0);
        let received: u64 = env.storage().instance().get(&DataKey::Received).unwrap_or(0);
        (sent, received)
    }

    fn check_text(env: &Env, text: &Bytes) {
        if text.len() == 0 {
            panic_with_error!(env, PostcardError::Empty);
        }
        if text.len() > MAX_TEXT_LEN {
            panic_with_error!(env, PostcardError::TooLong);
        }
    }
}

// snippet:start lzReceiveRust
impl LzReceiveInternal for PostcardOApp {
    fn __lz_receive(env: &Env, origin: &Origin, guid: &BytesN<32>, message: &Bytes, _extra_data: &Bytes, _executor: &Address, _value: i128) {
        // The generated lz_receive already checked that origin.sender is our peer for origin.src_eid
        // and cleared the payload on the endpoint. All that is left is our application logic.
        let card = Postcard {
            src_eid: origin.src_eid,
            sender: origin.sender.clone(),
            guid: guid.clone(),
            text: message.clone(),
            ledger: env.ledger().sequence(),
            timestamp: env.ledger().timestamp(),
        };
        let mut cards: Vec<Postcard> = env.storage().instance().get(&DataKey::Postcards).unwrap_or(Vec::new(env));
        cards.push_front(card);
        while cards.len() > MAX_POSTCARDS {
            cards.pop_back();
        }
        env.storage().instance().set(&DataKey::Postcards, &cards);
        let received: u64 = env.storage().instance().get(&DataKey::Received).unwrap_or(0);
        env.storage().instance().set(&DataKey::Received, &(received + 1));
        env.events().publish((symbol_short!("pc_recv"), origin.src_eid), (guid.clone(), message.clone()));
    }
}
// snippet:end lzReceiveRust
